config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'chatty#index'

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  post 'message', to: 'messages#create'

  get 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, uniqueness: {case_sensitive: false}, length: { minimum: 5, maximum: 20 }
    has_many :messages
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def require_user
      if !logged_in?
        flash[:error] = "You must be logged in to perform that action"
        redirect_to login_path
      end 
    end 

    def logged_in?
      !!current_user
    end 


end

app/controllers/chatty_controller.rb
class ChattyController < ApplicationController
  before_action :require_user 

  def index
    @message = Message.new
    @messages = Message.all
  end 

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :require_user


  def create
    message = current_user.messages.build(message_requirements)
    if message.save
        redirect_to root_path
    end 
  end 

  private

  def message_requirements
    params.require(:message).permit(:description)
  end 


end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_logged_in, only: [:new, :create]

  def new
  end 

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Alohomora!!! You have been successfully logged in"
      redirect_to root_path
    else
      flash.now[:error] = "Nox... unable to log in. Please check your username and/or password"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Alohormora!!! You have successfully been logged out"
    redirect_to login_path
  end

  private

  def already_logged_in
    if logged_in?
      flash[:error] =  "Merlin's Beard! You are already logged in"
      redirect_to root_path
    end 
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatty/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Home</title>
  <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">
  </head>
<body>
<h3>
  Alohomora......unlock the conversation!
</h3>
<i class="fa fa-hat-wizard"></i>
<h2 class="ui header">
  <img class="ui image" src="/images/icons/school.png">
</h2>
<div class="ui segment">
<img class="ui small image" src="/images/keyhogwarts.png">
</div>
<div class="dumbledore">
<img src="/keyhogwarts.png">
</div>

<img class="ui avatar image" src="/images/keyhogwarts.png">
<div class="ui small images">
</div>

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
    <div class="ui feed">
    <%= render @messages %>
    </div>
</div>
<div class="extra content">
<%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path) do |f| %>
<div class="field">
<div class="ui fluid icon input">
<%= f.text_field :description %>
<%= f.button '<i class="bordered inverted grey edit icon"></i>'.html_safe %>
</div>
</div>
<% end %>
</div>
</div>
</div>


<div class="four wide column">
  <div class="ui fluid raised card chatbox">
    <div class="content">
<div class="ui inverted vertical menu">
  <a class="active item">
    Home
  </a>
  <a class="item">
    Messages
  </a>
  <a class="item">
    Friends
  </a>
</div>
</div>
</div>
</div>
</div>
  
  </body>
  </html>
</body>
</html>

app/views/layouts/_messages.html.erb
<% flash.each do  |message_type, message_content| %>
    <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>

<% end %>

app/views/layouts/_navigation.html.erb
   <%= link_to "Chatty", root_path, class: "item" %>
     <a class="item">
        Potterhead Messages
      </a>
   
      <div class="ui stackable inverted menu">
      <div class="menu">
      <% if logged_in? %>
        <%= link_to "Logout", logout_path, method: :delete, class: "item" %>
      <% else %>
        <%= link_to "Login", login_path, class: "item" %>
      <% end %>
      </div>
      </div>
    
    <% if !logged_in? %>
      <%= link_to "Log in", login_path, class: "ui info button" %>
       
    </div>
    <% end %>
    </div>
     

      
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatty</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
      <div class="ui small inverted menu">
      <div class="ui container">
    <%= render 'layouts/navigation' %>
    </div>
    </div>
    <div class="ui container">
    <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%= message.description %>
    </div>
  </div>
</div>